[package]
name = "bevy"
version = "0.1.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
bevy = "0.12"
bevy_egui = "0.23"
egui_graphs = { path = "../../" }
petgraph = "0.6"
