[package]
name = "bevy_basic"
version = "0.1.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
egui_graphs = { path = "../.." }
bevy = "0.15.1"
bevy_egui = "0.32.0"
petgraph = "0.7.1"
