[package]
name = "bevy_basic"
version = "0.1.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
egui_graphs = "0.21"
bevy = "0.14"
bevy_egui = "0.29"
petgraph = "0.6"
